### ISSUE TITLE
missing three kurdish letters 

### ISSUE THREAD

**Issue by hamashexler** [omar84/arabic_writer#1]
Hi I hope you are still active your project is very creative, but there are three missing Kurdish letters 
most have a little letter on the letter looks like ٧ but we need to use it in Kurdish.
First
ێ 
(individual, start, middle, end)
ـێ ـێـ ێـ ێ
second 
ڕ
(individual, start, middle, end)
ڕ ـڕ ڕ ڕ
third
(individual, start, middle, end)
ـڵ ـڵـ ڵــ ڵ

**Comment by omar84** [comment]
@hamashexler sadly, there are no beginning, middle and end representations of these letters in unicode.
believe me, I tried finding every letter, and these were problematic.

thus, I'm closing this issue

**Comment by hamashexler** [comment]
thanks for the great project.
